administrator/urls.py
from django.urls import path

from . import views

app_name = 'administrator'
urlpatterns = [
    path('', views.index, name='index'),
    path('deptlist', views.deptlist, name='deptlist'),
]

collegemanagementsystem/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static


urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('administrator.urls')),
    path('student/', include('student.urls')),
    path('staff/', include('staff.urls')),
    path('api/', include('collegesystem_rest.urls'), name="api"),
]
# if settings.DEBUG:
urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)
urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

staff/urls.py
from django.urls import path

from . import views

app_name = 'staff'
urlpatterns = [
   path('', views.register, name='register'),
   path('savestaff', views.savestaff, name='savestaff'),
   path('loginpage/', views.loginpage, name='loginpage'),
   path('dologin', views.dologin, name='dologin'),
   path('staffhome/', views.staffhome, name='staffhome'),
   path('myprofile/', views.myprofile, name='myprofile'),
   path('staff_list_for_student', views.staff_list_for_student, name='staff_list_for_student'),
   path('staff_all_detail',views.staff_all_detail,name='staff_all_detail'),
   path('stafflogout', views.stafflogout, name='stafflogout'),
]

student/urls.py
from django.urls import path

from . import views

app_name = 'student'
urlpatterns = [
    path('', views.application, name='application'),
    path('studentapply',views.studentapply, name='student_apply'),
    path('register',views.register, name='register'),
    path('savestudent', views.savestudent, name='savestudent'),
    path('loginpage/', views.loginpage, name='loginpage'),
    path('dologin', views.dologin, name='dologin'),
    path('stuhome/', views.stuhome, name='stuhome'),
    path('myprofile/', views.myprofile, name='myprofile'),
    path('studetaillist', views.studetaillist, name='studetaillist'),
    path('studetaillistdeptwise/<str:dept_code>/',views.studetaillistdeptwise, name='studetaillistdeptwise'),
    path('stulogout/', views.stulogout, name='stulogout'),
]

student/views.py
from django.contrib import messages
from django.contrib.auth import authenticate, login, logout
from django.contrib.auth.decorators import login_required
from django.http import HttpResponseRedirect, HttpResponse
from django.shortcuts import render

# Create your views here.
from administrator.form import StudentApplicationForm
from administrator.models import Studentapplication, Studentregistration, MyUser, Department


def application(request):
    """
     Retrieving Student Application form with all fields and rendering
     Rendering Application Page for Student user from main page of college management system
     where Student application form is available
    """
    form = StudentApplicationForm()
    return render(request, 'student/application.html',{"form":form})

def studentapply(request):
    """
     If Student Application form is valid means Student user filling form with all the fields
     than form will save and student user redirect to main page of college management system
     otherwise on Application page form errors will show.
    """
    # Studentapplication.objects.create(name=request.POST.get('name'),email=request.POST.get('email'),ssc_marks=request.POST.get('ssc_marks'),internal_marks=request.POST.get('internal_marks'))
    if request.method =='POST':
        student_application_form = StudentApplicationForm(request.POST)
        if student_application_form.is_valid():
            student_application_form.save()
            return HttpResponseRedirect('/administrator')
        else:
            return render(request, 'student/application.html',{"error":student_application_form.errors, "form":StudentApplicationForm()})


def register(request):
    """
     Retrieving all objects of Student application and department and rendering
     Rendering on register page from main page of college management system
    """
    student = Studentapplication.objects.all()
    depts = Department.objects.all()
    return render(request, 'student/register.html',{'student':student, 'depts':depts})

def savestudent(request):
    """
     Retrieving email and checking student user approved by admin or not
     As MyUser is AbstractBase User, so for login authentication creating user with email and password.
     Retrieving department code
     Creating student user with authenticated user,dept code, and other Studentregistration's  model fields
     Rendering main page to college management system
    """
    student = Studentapplication.objects.get(email=request.POST.get('email'))
    if student.approved == False:
        messages.error(request, "Sorry, you are not approved by management so you can't do registration.")
        return HttpResponseRedirect('/student/register')
    else:
        user = MyUser.objects.create_user(email=request.POST.get('email'),password=request.POST.get('password'))
        deptObj = Department.objects.get(code=request.POST.get('dept'))
        Studentregistration.objects.create(studentApplication=student,father_name=request.POST.get('father_name'),mobile_no= request.POST.get('mobile_no'),
                                           dept=deptObj,profile_pic = request.FILES['profile_pic'],user=user)
        return render(request, 'administrator/index.html', {'message': "Congratulations !! You are successfully registered."})


def loginpage(request):
    """
         Rendering Student login page when staff user clicks on Staff Login
    """
    return render(request, 'student/login.html')

def dologin(request):
    """
         Authenticating of user with email and password on Login page
         if login successful then user redirects to the homepage
         if not successful then error message will show.
    """
    email = request.POST['email']
    password = request.POST['password']
    stu = authenticate(request, email=email, password=password)
    if stu is not None:
        login(request, stu)
        return HttpResponseRedirect('/student/stuhome/')
    else:
        return render(request, 'student/login.html', {'message': "Email and Password are not valid."})

@login_required(login_url='/student/loginpage/')
def stuhome(request):
    """
         Rendering student home page when student user successfully logged in.
    """
    print(request.user)
    print(request.user.studentregistration)
    print(request.user.studentregistration.dept)
    student = request.user.studentregistration
    return render(request, 'student/home.html',{'student':student})

@login_required(login_url='/student/loginpage/')
def myprofile(request):
    """
         Rendering student my profile page where logged in user related info is available.
    """
    student = request.user.studentregistration
    return render(request, 'student/myprofile.html',{'student':student})

@login_required(login_url='/student/loginpage/')
def studetaillist(request):
    """
    Retrieving student by applying filter department from student registration and rendering
    so only those students will display which have same department
    Rendering to student detail page
    """
    stu = request.user.studentregistration
    students = Studentregistration.objects.filter(dept=stu.dept)
    return render(request, 'student/student_detail.html',{'student':stu,'students':students})

@login_required(login_url='/staff/loginpage/')
def studetaillistdeptwise(request,dept_code):
    """
    Retrieving all students of Student registration
    Retrieving departments using dept code
    Checking if student's department code matches with department code then make a separate result
    and send it to with particular department wise on student detail list department wise page
    else send message that there is no student of this department
    """
    staff = request.user.staffregistration
    students = Studentregistration.objects.all()
    # print(student)
    dept = Department.objects.get(code=dept_code)
    result = []
    for s in students:
       if s.dept.code == dept_code:
          result.append(s)
    if result:
        return render(request, 'student/student_detaillist_departmentwise.html', {'staff': staff,'students': result, 'dept': dept})
    else:
        return render(request, 'student/student_detaillist_departmentwise.html',{'staff': staff, 'message': f"There are no students of {dept}", 'dept':dept})

def stulogout(request):
    """
         Logout function for student user with clearing and deleting session
    """
    request.session.clear()
    request.session.delete()
    logout(request)
    return HttpResponseRedirect("/student/loginpage/")

student/templates/student/login.html
<!DOCTYPE html>
<html lang="en">
{% load static %}
    <head>
        <meta charset="utf-8" />
        <meta http-equiv="X-UA-Compatible" content="IE=edge" />
        <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no" />
        <meta name="description" content="" />
        <meta name="author" content="" />
        <title>Student Login</title>
        <link href="{% static 'css/styles.css' %}" rel="stylesheet" />
        <script src="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/5.15.3/js/all.min.js" crossorigin="anonymous"></script>

    </head>
    <body class="bg-primary">
        <div id="layoutAuthentication">
            <div id="layoutAuthentication_content">
                <main>
                    <div class="container">
                        <div class="row justify-content-center">
                            <div class="col-lg-5">
                                <div class="card shadow-lg border-0 rounded-lg mt-5">
                                    <div class="card-header"><h3 class="text-center font-weight-light my-4">Student Login</h3></div>
                                    <div class="card-body">
                                        <form action="{% url 'student:dologin' %}" method="post">
                                            {% csrf_token %}
                                            <div class="form-group">
                                                <label class="small mb-1">Email</label>
                                                <input class="form-control py-4" name="email" type="email" placeholder="Enter email address" />
                                            </div>
                                            <div class="form-group">
                                                <label class="small mb-1">Password</label>
                                                <input class="form-control py-4" name="password" type="password" placeholder="Enter password" />
                                            </div>
                                            <div class ="form-group">
                                                <div class="button">
                                                    <input type="submit" value="Login" class="btn btn-primary">
                                                </div>
                                            </div>
                                </form>
                                </div>
                                    <div class="card-footer text-center">
                                        <div class="small"><a href="{% url 'student:register' %}">Need an account? Sign up!</a>
                                        </div>
                                    </div>
                                    <div class="card-footer text-center">
                                        <div class="small"><a href="{% url 'administrator:index' %}">Back</a></div>
                                    </div>

                            </div>

                        </div>
                    </div>
                    </div>
                </main>
            </div>
            <div id="layoutAuthentication_footer">
                <footer class="py-4 bg-light mt-auto">
                    <div class="container-fluid">
                        <div class="d-flex align-items-center justify-content-between small">
                            <div class="text-muted">Copyright &copy; Falguni Patel 2021</div>
                        </div>
                    </div>
                </footer>
            </div>
        </div>
        <script src="https://code.jquery.com/jquery-3.5.1.slim.min.js" crossorigin="anonymous"></script>
        <script src="https://cdn.jsdelivr.net/npm/bootstrap@4.6.0/dist/js/bootstrap.bundle.min.js" crossorigin="anonymous"></script>
        <script src="{% static 'js/scripts.js' %}"></script>
    </body>
</html>


<!--<h1 style="text-align: center">Student Login</h1>-->
<!--<br><br><br>-->
<!--<form action="{% url 'student:dologin' %}" method="post" >-->
<!--  {% csrf_token %}-->
<!--        <label>Email id: </label><br>-->
<!--        <input type="email" id="email" name="email"><br><br>-->
<!--        <label>Password: </label><br>-->
<!--        <input type="password" id="password" name="password"><br><br>-->
<!--        <input type="submit" value="Login"><br><br>-->
<!--</form>-->
<!--    <a href="{% url 'administrator:index' %}">Back</a>-->

student/templates/student/myprofile.html
<!DOCTYPE html>
<html>
{% load static %}
<head>
  <meta charset="utf-8">
  <meta http-equiv="X-UA-Compatible" content="IE=edge">
  <title>My Profile</title>
  <!-- Tell the browser to be responsive to screen width -->
  <meta name="viewport" content="width=device-width, initial-scale=1">
  <!-- Font Awesome -->
  <link rel="stylesheet" href="{% static 'plugins/fontawesome-free/css/all.min.css' %}">
  <!-- Ionicons -->
  <link rel="stylesheet" href="https://code.ionicframework.com/ionicons/2.0.1/css/ionicons.min.css">
  <!-- Theme style -->
  <link rel="stylesheet" href="{% static 'dist/css/adminlte.min.css' %}">
  <!-- Google Font: Source Sans Pro -->
  <link href="https://fonts.googleapis.com/css?family=Source+Sans+Pro:300,400,400i,700" rel="stylesheet">
  <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.5.1/jquery.min.js"></script>
  <script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.4.1/js/bootstrap.min.js"></script>
  <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/font-awesome/4.7.0/css/font-awesome.min.css">
</head>
<style>
.signout{
margin:0 0 0 770px;
display:inline-flex;
list style: none;
}
</style>
<body>
    <nav class="main-header navbar navbar-expand navbar-white navbar-light">
        <!-- Left navbar links -->
        <ul class="navbar-nav">
          <li class="nav-item">
            <a class="nav-link" data-widget="pushmenu" href="#"><i class="fas fa-bars"></i></a>
          </li>
          <li class="nav-item d-none d-sm-inline-block">
            <a href="{% url 'student:stuhome' %} " class="nav-link"><i class="fa fa-home"></i>  Home</a>
          </li>
          <div class="signout">
           <a href="{% url 'student:stulogout' %}" class="nav-link"><i class="fa fa-sign-out"></i>  Logout</a>
           </div>
        </ul>
    </nav>

    <!-- Main Sidebar Container -->
  <aside class="main-sidebar sidebar-dark-primary elevation-4">

    <!-- Sidebar -->
    <div class="sidebar">
      <!-- Sidebar user panel (optional) -->
      <div class="user-panel mt-3 pb-2 mb-3 d-flex">
        <div class="image">
          <img src="/media/{{student.profile_pic}}" style="width:30px;height:30px;" class="img-circle elevation-2" alt="User Image">
        </div>
        <div class="info">
          <a href="{% url 'student:myprofile' %}" class="d-block" >{{student.studentApplication.name}}</a>
        </div>
      </div>

     <nav class="mt-2">
        <ul class="nav nav-pills nav-sidebar flex-column" data-widget="treeview" role="menu" data-accordion="false">
          <!-- Add icons to the links using the .nav-icon class
               with font-awesome or any other icon font library -->
           <li class="nav-item has-treeview">
            <a href="#" class="nav-link">
              <i class="nav-icon fas fa-copy"></i>
              <p>
                Details
                <i class="fas fa-angle-left right"></i>
                <span class="badge badge-info right"></span>
              </p>
            </a>
            <ul class="nav nav-treeview">
              <li class="nav-item">
                <a href="{% url 'student:studetaillist' %}" class="nav-link">
                  <i class="far fa-circle nav-icon"></i>
                  <p>Student List</p>
                </a>
              </li>
              <li class="nav-item">
                <a href="{% url 'staff:staff_list_for_student' %}" class="nav-link">
                  <i class="far fa-circle nav-icon"></i>
                  <p>Staff List</p>
                </a>
              </li>
            </ul>
           </li>
            <li class="nav-item has-treeview">
            <a href="#" class="nav-link">
              <i class="nav-icon fas fa-book"></i>
              <p>
                Pages
                <i class="fas fa-angle-left right"></i>
              </p>
            </a>
            <ul class="nav nav-treeview">
              <li class="nav-item">
                <a href="{% url 'student:myprofile' %}"class="nav-link">
                  <i class="far fa-circle nav-icon"></i>
                  <p>My Profile</p>
                </a>
              </li>
              <li class="nav-item">
                <a href="{% url 'student:stulogout' %}" class="nav-link">
                  <i class="far fa-circle nav-icon"></i>
                  <p>Logout</p>
                </a>
              </li>
             </ul>
          </li>
        </ul>
        <div class="sb-sidenav-footer">
            <div style="margin:0 0 390px 0"></div>
            Logged In As: Student
        </div>
     </nav>
    </div>
    </aside>

    <!-- Content Wrapper. Contains page content -->
  <div class="content-wrapper">
    <!-- Content Header (Page header) -->
    <section class="content-header">
      <div class="container-fluid">
        <div class="row mb-2">
          <div class="col-sm-6">
            <h1>My Profile</h1>
          </div>
        </div>
      </div><!-- /.container-fluid -->
    </section>

     <!-- Main content -->
    <section class="content">
      <div class="container-fluid">
        <div class="row">
          <div class="col-12">
            <!-- Default box -->
            <div class="card">
              <div class="card-header">
                <h3 class="card-title"><label><b>Name: </b></label> {{student.studentApplication.name}}</h3>
                <div class="card-tools">
                  <button type="button" class="btn btn-tool" data-card-widget="collapse" data-toggle="tooltip" title="Collapse">
                    <i class="fas fa-minus"></i></button>
                  <button type="button" class="btn btn-tool" data-card-widget="remove" data-toggle="tooltip" title="Remove">
                    <i class="fas fa-times"></i></button>
                </div>
              </div>
              <div class="card-body">
                <label><b>Profile pic: </b></label>
                <img align="right" src="/media/{{student.profile_pic}}" style="width:100px;height:100px;"><br>
                <label><b>Email: </b></label> {{student.studentApplication.email}}<br>
                <label><b>Department: </b></label> {{student.dept}}<br>
                <label><b>SSC Marks: </b></label> {{student.studentApplication.ssc_marks}}<br>
                <label><b>Internal Marks: </b></label> {{student.studentApplication.internal_marks}}
              </div>
              <!-- /.card-body -->

            <!-- /.card -->
          </div>
        </div>
      </div>
      </div>
    </section>
    <!-- /.content -->
  </div>
  <!-- /.content-wrapper -->

    <script src="https://code.jquery.com/jquery-3.5.1.slim.min.js" crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@4.6.0/dist/js/bootstrap.bundle.min.js" crossorigin="anonymous"></script>
    <script src="{% static 'js/scripts.js' %}"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/Chart.js/2.8.0/Chart.min.js" crossorigin="anonymous"></script>
    <script src="{% static 'assets/demo/chart-area-demo.js' %}"></script>
    <script src="{% static 'assets/demo/chart-bar-demo.js' %}"></script>
    <script src="https://cdn.datatables.net/1.10.20/js/jquery.dataTables.min.js" crossorigin="anonymous"></script>
    <script src="https://cdn.datatables.net/1.10.20/js/dataTables.bootstrap4.min.js" crossorigin="anonymous"></script>
    <script src="{% static 'assets/demo/datatables-demo.js' %}"></script>
    <!-- jQuery -->
    <script src="{% static 'plugins/jquery/jquery.min.js' %}"></script>
    <!-- Bootstrap 4 -->
    <script src="{% static 'plugins/bootstrap/js/bootstrap.bundle.min.js' %}"></script>
    <!-- AdminLTE App -->
    <script src="{% static 'dist/js/adminlte.min.js' %}"></script>
    <!-- AdminLTE for demo purposes -->
    <script src="{% static 'dist/js/demo.js' %}"></script>
</body>
</html>

student/templates/student/student_detail.html
<!DOCTYPE html>
<html>
{% load static %}
<head>
  <meta charset="utf-8">
  <meta http-equiv="X-UA-Compatible" content="IE=edge">
  <title>Student List</title>
  <!-- Tell the browser to be responsive to screen width -->
  <meta name="viewport" content="width=device-width, initial-scale=1">
  <!-- Font Awesome -->
  <link rel="stylesheet" href="{% static 'plugins/fontawesome-free/css/all.min.css' %}">
  <!-- Ionicons -->
  <link rel="stylesheet" href="https://code.ionicframework.com/ionicons/2.0.1/css/ionicons.min.css">
  <!-- DataTables -->
  <link rel="stylesheet" href="{% static 'plugins/datatables-bs4/css/dataTables.bootstrap4.css' %}">
  <!-- Theme style -->
  <link rel="stylesheet" href="{% static 'dist/css/adminlte.min.css' %}">
  <!-- Google Font: Source Sans Pro -->
  <link href="https://fonts.googleapis.com/css?family=Source+Sans+Pro:300,400,400i,700' %}" rel="stylesheet">
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.5.1/jquery.min.js"></script>
    <script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.4.1/js/bootstrap.min.js"></script>
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/font-awesome/4.7.0/css/font-awesome.min.css">
</head>
<style>
.signout{
margin:0 0 0 770px;
display:inline-flex;
list style: none;
}
</style>
<body>
    <nav class="main-header navbar navbar-expand navbar-white navbar-light">
        <!-- Left navbar links -->
        <ul class="navbar-nav">
          <li class="nav-item">
            <a class="nav-link" data-widget="pushmenu" href="#"><i class="fas fa-bars"></i></a>
          </li>
          <li class="nav-item d-none d-sm-inline-block">
            <a href="{% url 'student:stuhome' %} " class="nav-link"><i class="fa fa-home"></i>  Home</a>
          </li>
          <div class="signout">
           <a href="{% url 'student:stulogout' %}" class="nav-link"><i class="fa fa-sign-out"></i>  Logout</a>
           </div>
        </ul>
    </nav>

    <!-- Main Sidebar Container -->
  <aside class="main-sidebar sidebar-dark-primary elevation-4">

    <!-- Sidebar -->
    <div class="sidebar">
      <!-- Sidebar user panel (optional) -->
      <div class="user-panel mt-3 pb-2 mb-3 d-flex">
        <div class="image">
          <img src="/media/{{student.profile_pic}}" style="width:30px;height:30px;" class="img-circle elevation-2" alt="User Image">
        </div>
        <div class="info">
          <a href="{% url 'student:myprofile' %}" class="d-block" >{{student.studentApplication.name}}</a>
        </div>
      </div>


     <nav class="mt-2">
        <ul class="nav nav-pills nav-sidebar flex-column" data-widget="treeview" role="menu" data-accordion="false">
          <!-- Add icons to the links using the .nav-icon class
               with font-awesome or any other icon font library -->
           <li class="nav-item has-treeview">
            <a href="#" class="nav-link">
              <i class="nav-icon fas fa-copy"></i>
              <p>
                Details
                <i class="fas fa-angle-left right"></i>
                <span class="badge badge-info right"></span>
              </p>
            </a>
            <ul class="nav nav-treeview">
              <li class="nav-item">
                <a href="{% url 'student:studetaillist' %}" class="nav-link">
                  <i class="far fa-circle nav-icon"></i>
                  <p>Student List</p>
                </a>
              </li>
              <li class="nav-item">
                <a href="{% url 'staff:staff_list_for_student' %}" class="nav-link">
                  <i class="far fa-circle nav-icon"></i>
                  <p>Staff List</p>
                </a>
              </li>
            </ul>
           </li>
            <li class="nav-item has-treeview">
            <a href="#" class="nav-link">
              <i class="nav-icon fas fa-book"></i>
              <p>
                Pages
                <i class="fas fa-angle-left right"></i>
              </p>
            </a>
            <ul class="nav nav-treeview">
              <li class="nav-item">
                <a href="{% url 'student:myprofile' %}" class="nav-link">
                  <i class="far fa-circle nav-icon"></i>
                  <p>My Profile</p>
                </a>
              </li>
              <li class="nav-item">
                <a href="{% url 'student:stulogout' %}" class="nav-link">
                  <i class="far fa-circle nav-icon"></i>
                  <p>Logout</p>
                </a>
              </li>
             </ul>
          </li>
        </ul>
        <div class="sb-sidenav-footer">
            <div style="margin:0 0 390px 0"></div>
            Logged In As: Student
        </div>
     </nav>
    </div>
    </aside>
     <div class="content-wrapper">
    <!-- Content Header (Page header) -->
    <section class="content-header">
      <div class="container-fluid">
        <div class="row mb-2">
          <div class="col-sm-6">
            <h1>Student List</h1>
          </div>
        </div>
      </div><!-- /.container-fluid -->
    </section>

    <!-- Main content -->
    <section class="content">
      <div class="row">
        <div class="col-12">
         <div class="card">
            <!-- /.card-header -->
            <div class="card-body">
              <table id="example1" class="table table-bordered table-striped">
                <thead>
                <tr>
                  <th>Roll No</th>
                  <th>Name</th>
                  <th>Email</th>
                </tr>
                </thead>
                <tbody>
                {% for s in students %}
                  <tr>
                    <td>{{s.id|stringformat:"04d"}}</td>
                    <td>{{s.studentApplication.name}}</td>
                    <td>{{s.studentApplication.email}}</td>
                  </tr>
                {% endfor %}
                </tbody>
              </table>
            </div>
         </div>
        </div>
      </div>
    </section>
     </div>
    <script src="https://code.jquery.com/jquery-3.5.1.slim.min.js" crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@4.6.0/dist/js/bootstrap.bundle.min.js" crossorigin="anonymous"></script>
    <script src="{% static 'js/scripts.js' %}"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/Chart.js/2.8.0/Chart.min.js" crossorigin="anonymous"></script>
    <script src="{% static 'assets/demo/chart-area-demo.js' %}"></script>
    <script src="{% static 'assets/demo/chart-bar-demo.js' %}"></script>
    <script src="https://cdn.datatables.net/1.10.20/js/jquery.dataTables.min.js" crossorigin="anonymous"></script>
    <script src="https://cdn.datatables.net/1.10.20/js/dataTables.bootstrap4.min.js" crossorigin="anonymous"></script>
    <script src="{% static 'assets/demo/datatables-demo.js' %}"></script>
<!-- jQuery -->
<script src="{% static 'plugins/jquery/jquery.min.js' %}"></script>
<!-- Bootstrap 4 -->
<script src="{% static 'plugins/bootstrap/js/bootstrap.bundle.min.js' %}"></script>
<!-- DataTables -->
<script src="{% static 'plugins/datatables/jquery.dataTables.js' %}"></script>
<script src="{% static 'plugins/datatables-bs4/js/dataTables.bootstrap4.js' %}"></script>
<!-- AdminLTE App -->
<script src="{% static 'dist/js/adminlte.min.js' %}"></script>
<!-- AdminLTE for demo purposes -->
<script src="{% static 'dist/js/demo.js' %}"></script>
<!-- page script -->
<script>
  $(function () {
    $("#example1").DataTable();
    $('#example2').DataTable({
      "paging": true,
      "lengthChange": false,
      "searching": false,
      "ordering": true,
      "info": true,
      "autoWidth": false,
    });
  });
</script>
</body>
</html>

<!--<style>-->
<!--table, th, td {-->
<!--  border: 1px solid black;-->
<!--  border-collapse: collapse;-->
<!--  outline:1px solid black;-->
<!--}-->
<!--table.center {-->
<!--  margin-left: auto;-->
<!--  margin-right: auto;-->
<!--}-->
<!--th, td {-->
<!--  padding: 15px;-->
<!--  text-align:center;-->
<!--}-->
<!--th{-->
<!--font-size:20px;-->
<!--color:blue-->
<!--}-->
<!--.border{-->
<!--padding:15px;-->
<!--border: 1px solid sienna;-->
<!--outline:1px dotted sienna;-->
<!--}-->
<!--</style>-->

<!--<div style="text-align: right">-->
<!--  <a href="{% url 'student:stulogout' %}">Logout</a>-->
<!--</div>-->
<!--<h1 style="text-align: center">Students Detail Page</h1>-->
<!--<br><br><br>-->

<!--<div class="table">-->
<!--  <table class="center">-->
<!--  <tr>-->
<!--    <th>RollNo</th>-->
<!--    <th>Name</th>-->
<!--    <th>Email</th>-->
<!--  </tr>-->

<!--{% for s in students %}-->
<!--    <tr>-->
<!--      <td>{{s.id|stringformat:"04d"}}</td>-->
<!--      <td>{{s.studentApplication.name}}</td>-->
<!--      <td>{{s.studentApplication.email}}</td>-->
<!--    </tr>-->
<!--{% endfor %}-->
<!--</table>-->
<!--</div>-->

<!--<br><br><br>-->
<!--<a href="{% url 'student:stuhome' %}">Back</a>-->