administrator/urls.py
from django.urls import path

from . import views

app_name = 'administrator'
urlpatterns = [
    path('', views.index, name='index'),
    path('deptlist', views.deptlist, name='deptlist'),
]

collegemanagementsystem/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static


urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('administrator.urls')),
    path('student/', include('student.urls')),
    path('staff/', include('staff.urls')),
    path('api/', include('collegesystem_rest.urls'), name="api"),
]
# if settings.DEBUG:
urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)
urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

staff/urls.py
from django.urls import path

from . import views

app_name = 'staff'
urlpatterns = [
   path('', views.register, name='register'),
   path('savestaff', views.savestaff, name='savestaff'),
   path('loginpage/', views.loginpage, name='loginpage'),
   path('dologin', views.dologin, name='dologin'),
   path('staffhome/', views.staffhome, name='staffhome'),
   path('myprofile/', views.myprofile, name='myprofile'),
   path('staff_list_for_student', views.staff_list_for_student, name='staff_list_for_student'),
   path('staff_all_detail',views.staff_all_detail,name='staff_all_detail'),
   path('stafflogout', views.stafflogout, name='stafflogout'),
]

student/urls.py
from django.urls import path

from . import views

app_name = 'student'
urlpatterns = [
    path('', views.application, name='application'),
    path('studentapply',views.studentapply, name='student_apply'),
    path('register',views.register, name='register'),
    path('savestudent', views.savestudent, name='savestudent'),
    path('loginpage/', views.loginpage, name='loginpage'),
    path('dologin', views.dologin, name='dologin'),
    path('stuhome/', views.stuhome, name='stuhome'),
    path('myprofile/', views.myprofile, name='myprofile'),
    path('studetaillist', views.studetaillist, name='studetaillist'),
    path('studetaillistdeptwise/<str:dept_code>/',views.studetaillistdeptwise, name='studetaillistdeptwise'),
    path('stulogout/', views.stulogout, name='stulogout'),
]

administrator/models.py
from django.db import models
from django.contrib.auth.models import (BaseUserManager,AbstractBaseUser)

# Create your models here.
from django.db.models import OneToOneField


class UserManager(BaseUserManager):
    def create_user(self, email, password=None):
        if not email:
            raise ValueError("Users must have an email address")

        user = self.model(
            email=self.normalize_email(email),
             )
        user.set_password(password)
        user.save(using=self._db)
        return user

    def create_superuser(self, email ,password=None):
        user = self.create_user(
            email,
            password=password,
        )
        user.is_admin=True
        user.save(using=self._db)
        return user

class MyUser(AbstractBaseUser):
    """
      with this MyUser, trying to create authentication with email and password
    """
    email = models.EmailField(
        verbose_name='email address',
        max_length=255,
        unique=True,
    )

    is_active = models.BooleanField(default=True)
    is_admin = models.BooleanField(default=False)

    objects = UserManager()

    USERNAME_FIELD = 'email'
    REQUIRED_FIELDS = []

    def __str__(self):
        return self.email

    def has_perm(self, perm, obj=None):
        return True

    def has_module_perms(self, app_label):
        return True

    @property
    def is_staff(self):
        return self.is_admin



class Studentapplication(models.Model):
    name = models.CharField(max_length=255)
    email = models.EmailField(
        verbose_name='email address',
        max_length=255,
        unique=True,
    )
    ssc_marks = models.IntegerField()
    internal_marks = models.IntegerField()
    approved = models.BooleanField(default=False)

    def __str__(self):
        return self.email

class Department(models.Model):
    code = models.CharField(max_length=20)
    name = models.CharField(max_length=20)

    def __str__(self):
        return self.code


class Studentregistration(models.Model):
    studentApplication = models.OneToOneField(Studentapplication, on_delete=models.CASCADE)
    user = models.OneToOneField(MyUser, on_delete=models.CASCADE, default=True)
    father_name = models.CharField(max_length=255)
    mobile_no = models.IntegerField()
    dept = models.ForeignKey(Department, on_delete=models.CASCADE)
    profile_pic = models.ImageField(upload_to='studentimages/')

    def __str__(self):
        return self.studentApplication.email


class Staffregistration(models.Model):
    user = models.OneToOneField(MyUser, on_delete=models.CASCADE, default=True)
    name = models.CharField(max_length=255)
    mobile_no = models.IntegerField()
    dept = models.ForeignKey(Department, on_delete=models.CASCADE)
    exp = models.IntegerField()
    qualification = models.CharField(max_length=255)
    profile_pic = models.ImageField(upload_to='staffimages/')

    def __str__(self):
        return self.user.email

administrator/views.py
from django.contrib.auth.decorators import login_required
from django.shortcuts import render

# Create your views here.
from administrator.models import Department


def index(request):
    """
      Main page of college management system
    """
    return render(request, 'administrator/index.html')

@login_required(login_url='/staff/loginpage/')
def deptlist(request):
    """
      Created for staff app, rendering all department's objects
      using this staff can see which student is from which department
    """
    staff = request.user.staffregistration
    departments = Department.objects.all()
    return render(request, 'administrator/deptlist.html',{'staff': staff,'departments':departments})

administrator/templates/administrator/deptlist.html
<!DOCTYPE html>
<html>
{% load static %}
<head>
  <meta charset="utf-8">
  <meta http-equiv="X-UA-Compatible" content="IE=edge">
  <title>Student Detail Department Wise</title>
  <!-- Tell the browser to be responsive to screen width -->
  <meta name="viewport" content="width=device-width, initial-scale=1">
  <!-- Font Awesome -->
  <link rel="stylesheet" href="{% static 'plugins/fontawesome-free/css/all.min.css' %}">
  <!-- Ionicons -->
  <link rel="stylesheet" href="https://code.ionicframework.com/ionicons/2.0.1/css/ionicons.min.css">
  <!-- DataTables -->
  <link rel="stylesheet" href="{% static 'plugins/datatables-bs4/css/dataTables.bootstrap4.css' %}">
  <!-- Theme style -->
  <link rel="stylesheet" href="{% static 'dist/css/adminlte.min.css' %}">
  <!-- Google Font: Source Sans Pro -->
  <link href="https://fonts.googleapis.com/css?family=Source+Sans+Pro:300,400,400i,700' %}" rel="stylesheet">
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.5.1/jquery.min.js"></script>
    <script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.4.1/js/bootstrap.min.js"></script>
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/font-awesome/4.7.0/css/font-awesome.min.css">
</head>
<style>
.signout{
margin:0 0 0 770px;
display:inline-flex;
list style: none;
}
</style>
<body>
    <nav class="main-header navbar navbar-expand navbar-white navbar-light">
        <!-- Left navbar links -->
        <ul class="navbar-nav">
          <li class="nav-item">
            <a class="nav-link" data-widget="pushmenu" href="#"><i class="fas fa-bars"></i></a>
          </li>
          <li class="nav-item d-none d-sm-inline-block">
            <a href="{% url 'staff:staffhome' %}" class="nav-link"><i class="fa fa-home"></i>  Home</a>

          </li>
           <div class="signout">
           <a href="{% url 'staff:stafflogout' %}" class="nav-link"><i class="fa fa-sign-out"></i>  Logout</a>
           </div>
        </ul>
    </nav>

    <!-- Main Sidebar Container -->
  <aside class="main-sidebar sidebar-dark-primary elevation-4">

    <!-- Sidebar -->
    <div class="sidebar">
      <!-- Sidebar user panel (optional) -->
      <div class="user-panel mt-3 pb-2 mb-3 d-flex">
        <div class="image">
          <img src="/media/{{staff.profile_pic}}" style="width:30px;height:30px;" class="img-circle elevation-2" alt="User Image">
        </div>
        <div class="info">
          <a href="{% url 'staff:myprofile' %}" class="d-block" >{{staff.name}}</a>
        </div>
      </div>


     <nav class="mt-2">
        <ul class="nav nav-pills nav-sidebar flex-column" data-widget="treeview" role="menu" data-accordion="false">
          <!-- Add icons to the links using the .nav-icon class
               with font-awesome or any other icon font library -->
           <li class="nav-item has-treeview">
            <a href="#" class="nav-link">
              <i class="nav-icon fas fa-copy"></i>
              <p>
                Details
                <i class="fas fa-angle-left right"></i>
                <span class="badge badge-info right"></span>
              </p>
            </a>
            <ul class="nav nav-treeview">
              <li class="nav-item">
                <a href="{% url 'administrator:deptlist' %}" class="nav-link">
                  <i class="far fa-circle nav-icon"></i>
                  <p>Student List</p>
                </a>
              </li>
              <li class="nav-item">
                <a href="{% url 'staff:staff_all_detail' %}" class="nav-link">
                  <i class="far fa-circle nav-icon"></i>
                  <p>Staff List</p>
                </a>
              </li>
            </ul>
           </li>
            <li class="nav-item has-treeview">
            <a href="#" class="nav-link">
              <i class="nav-icon fas fa-book"></i>
              <p>
                Pages
                <i class="fas fa-angle-left right"></i>
              </p>
            </a>
            <ul class="nav nav-treeview">
              <li class="nav-item">
                <a href="{% url 'staff:myprofile' %}" class="nav-link">
                  <i class="far fa-circle nav-icon"></i>
                  <p>My Profile</p>
                </a>
              </li>
              <li class="nav-item">
                <a href="{% url 'staff:stafflogout' %}" class="nav-link">
                  <i class="far fa-circle nav-icon"></i>
                  <p>Logout</p>
                </a>
              </li>
             </ul>
          </li>
        </ul>
        <div class="sb-sidenav-footer">
            <div style="margin:0 0 390px 0"></div>
            Logged In As: Staff
        </div>
     </nav>
    </div>
    </aside>

     <div class="content-wrapper">
    <!-- Content Header (Page header) -->
    <section class="content-header">
      <div class="container-fluid">
        <div class="row mb-2">
          <div class="col-sm-6">
            <h1>Student List Department Wise</h1>
          </div>
        </div>
      </div><!-- /.container-fluid -->
    </section>

    <!-- Main content -->
    <section class="content">
      <div class="row">
        <div class="col-12">
         <div class="card">
            <!-- /.card-header -->
            <div class="card-body">
              <table id="example1" class="table table-bordered table-striped">
                <thead>
                <tr>
                  <th>Code</th>
                  <th>Name</th>
                </tr>
                </thead>
                <tbody>
                {% for dept in departments %}
                  <tr>
                     <td><a href="{% url 'student:studetaillistdeptwise' dept.code %}">{{dept.code}}</a></td>
                     <td>{{dept.name}}</td>
                  </tr>
                  {% endfor %}
                </tbody>
              </table>
            </div>
         </div>
        </div>
      </div>
    </section>
     </div>
    <script src="https://code.jquery.com/jquery-3.5.1.slim.min.js" crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@4.6.0/dist/js/bootstrap.bundle.min.js" crossorigin="anonymous"></script>
    <script src="{% static 'js/scripts.js' %}"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/Chart.js/2.8.0/Chart.min.js" crossorigin="anonymous"></script>
    <script src="{% static 'assets/demo/chart-area-demo.js' %}"></script>
    <script src="{% static 'assets/demo/chart-bar-demo.js' %}"></script>
    <script src="https://cdn.datatables.net/1.10.20/js/jquery.dataTables.min.js" crossorigin="anonymous"></script>
    <script src="https://cdn.datatables.net/1.10.20/js/dataTables.bootstrap4.min.js" crossorigin="anonymous"></script>
    <script src="{% static 'assets/demo/datatables-demo.js' %}"></script>
<!-- jQuery -->
<script src="{% static 'plugins/jquery/jquery.min.js' %}"></script>
<!-- Bootstrap 4 -->
<script src="{% static 'plugins/bootstrap/js/bootstrap.bundle.min.js' %}"></script>
<!-- DataTables -->
<script src="{% static 'plugins/datatables/jquery.dataTables.js' %}"></script>
<script src="{% static 'plugins/datatables-bs4/js/dataTables.bootstrap4.js' %}"></script>
<!-- AdminLTE App -->
<script src="{% static 'dist/js/adminlte.min.js' %}"></script>
<!-- AdminLTE for demo purposes -->
<script src="{% static 'dist/js/demo.js' %}"></script>
<!-- page script -->
<script>
  $(function () {
    $("#example1").DataTable();
    $('#example2').DataTable({
      "paging": true,
      "lengthChange": false,
      "searching": false,
      "ordering": true,
      "info": true,
      "autoWidth": false,
    });
  });
</script>
</body>
</html>

<!--<style>-->
<!--table, th, td {-->
<!--  border: 1px solid black;-->
<!--  border-collapse: collapse;-->
<!--  outline:1px solid black;-->
<!--}-->
<!--table.center {-->
<!--  margin-left: auto;-->
<!--  margin-right: auto;-->
<!--}-->
<!--th, td {-->
<!--  padding: 15px;-->
<!--  text-align:center;-->
<!--}-->
<!--th{-->
<!--font-size:20px;-->
<!--color:blue-->
<!--}-->
<!--.border{-->
<!--padding:15px;-->
<!--border: 1px solid sienna;-->
<!--outline:1px dotted sienna;-->
<!--}-->
<!--</style>-->
<!--<div style="text-align: right">-->
<!--        <a href="{% url 'staff:loginpage' %}">Logout</a>-->
<!--</div>-->
<!--<h1 style="text-align: center">College Department List</h1>-->
<!--<br><br><br>-->

<!--<div class="table">-->
<!--  <table class="center">-->
<!--  <tr>-->
<!--      <th>Code</th>-->
<!--      <th>Name</th>-->
<!--  </tr>-->
<!--  {% for dept in departments %}-->
<!--  <tr>-->
<!--      <td><a href="{% url 'student:studetaillistdeptwise' dept.code %}">{{dept.code}}</a></td>-->
<!--      <td>{{dept.name}}</td>-->
<!--  </tr>-->
<!--  {% endfor %}-->
<!--  </table>-->
<!--</div>-->

<!--<a href="{% url 'staff:staffhome' %}">Back</a>-->

administrator/templates/administrator/index.html
<!DOCTYPE html>
<html lang="en">
{% load static %}
    <head>
        <meta charset="utf-8" />
        <meta http-equiv="X-UA-Compatible" content="IE=edge" />
        <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no" />
        <meta name="description" content="" />
        <meta name="author" content="" />
        <title>College Management System</title>
        <link href="{% static 'css/styles.css' %}" rel="stylesheet" />
        <!-- Tell the browser to be responsive to screen width -->
      <meta name="viewport" content="width=device-width, initial-scale=1">
      <!-- Font Awesome -->
      <link rel="stylesheet" href="{% static 'plugins/fontawesome-free/css/all.min.css' %}">
      <!-- Ionicons -->
      <link rel="stylesheet" href="https://code.ionicframework.com/ionicons/2.0.1/css/ionicons.min.css">
      <!-- DataTables -->
      <link rel="stylesheet" href="{% static 'plugins/datatables-bs4/css/dataTables.bootstrap4.css' %}">
      <!-- Theme style -->
      <link rel="stylesheet" href="{% static 'dist/css/adminlte.min.css' %}">
      <!-- Google Font: Source Sans Pro -->
      <link href="https://fonts.googleapis.com/css?family=Source+Sans+Pro:300,400,400i,700' %}" rel="stylesheet">
    </head>
<style>
body
{
background-image:url("https://images.unsplash.com/photo-1604098027975-91a63cb3a6ea?ixid=MnwxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8&ixlib=rb-1.2.1&auto=format&fit=crop&w=1489&q=80");
background-size:cover;
background-position:center;
}
</style>
    <body class="sb-nav-fixed">
        <nav class="sb-topnav navbar navbar-expand navbar-dark bg-dark">
            <button class="btn btn-link btn-sm order-1 order-lg-0" id="sidebarToggle" href="#!"><i class="fas fa-bars"></i></button>

            <!-- Header -->
            <div class="navbar-brand" style="color:white;font-size:30px;margin-left:420px;margin-right:300px;">College Management System</div>

            <form class="d-none d-md-inline-block form-inline ml-auto mr-0 mr-md-3 my-2 my-md-0">
            </form>
        </nav>

        <!-- Sidebar -->

        <div id="layoutSidenav">
            <div id="layoutSidenav_nav">
                <nav class="sb-sidenav accordion sb-sidenav-dark" id="sidenavAccordion">
                    <div class="sb-sidenav-menu">
                        <div class="nav">
                            <div class="collapse" id="collapseLayouts" aria-labelledby="headingOne" data-parent="#sidenavAccordion">
                                <nav class="sb-sidenav-menu-nested nav">
                                    <a class="nav-link" href="{% static 'layout-static.html' %}">Static Navigation</a>
                                    <a class="nav-link" href="{% static 'layout-sidenav-light.html' %}">Light Sidenav</a>
                                </nav>
                            </div>
                            <a class="nav-link collapsed" href="#" style="font-size:20px;" data-toggle="collapse" data-target="#collapsePages" aria-expanded="false" aria-controls="collapsePages">
                                <div class="sb-nav-link-icon"><i class="fas fa-book-open"></i></div>
                                Pages
                                <div class="sb-sidenav-collapse-arrow"><i class="fas fa-angle-down"></i></div>
                            </a>
                            <div class="collapse" id="collapsePages" aria-labelledby="headingTwo" data-parent="#sidenavAccordion">
                                <nav class="sb-sidenav-menu-nested nav accordion" id="sidenavAccordionPages">
                                    <a class="nav-link collapsed" href="#" data-toggle="collapse" data-target="#pagesCollapseAuth" aria-expanded="false" aria-controls="pagesCollapseAuth">
                                        Authentication
                                        <div class="sb-sidenav-collapse-arrow"><i class="fas fa-angle-down"></i></div>
                                    </a>
                                    <div class="collapse" id="pagesCollapseAuth" aria-labelledby="headingOne" data-parent="#sidenavAccordionPages">
                                        <nav class="sb-sidenav-menu-nested nav">
                                            <a class="nav-link" href="{% url 'student:application' %}">Student Application</a>
                                            <a class="nav-link" href="{% url 'student:register' %}">Student Registration</a>
                                            <a class="nav-link" href="{% url 'student:loginpage' %}">Student Login</a>
                                            <a class="nav-link" href="{% url 'staff:register' %}">Staff Registration</a>
                                            <a class="nav-link" href="{% url 'staff:loginpage' %}">Staff Login</a>
                                        </nav>
                                    </div>

                                </nav>
                                </div>
                           </div>
                          </div>
                          </nav>
                       </div>
                   </div>

    <script src="https://code.jquery.com/jquery-3.5.1.slim.min.js" crossorigin="anonymous"></script>
        <script src="https://cdn.jsdelivr.net/npm/bootstrap@4.6.0/dist/js/bootstrap.bundle.min.js" crossorigin="anonymous"></script>
        <script src="{% static 'js/scripts.js' %}"></script>
        <script src="https://cdnjs.cloudflare.com/ajax/libs/Chart.js/2.8.0/Chart.min.js" crossorigin="anonymous"></script>
        <script src="{% static 'assets/demo/chart-area-demo.js' %}"></script>
        <script src="{% static 'assets/demo/chart-bar-demo.js' %}"></script>
        <script src="https://cdn.datatables.net/1.10.20/js/jquery.dataTables.min.js" crossorigin="anonymous"></script>
        <script src="https://cdn.datatables.net/1.10.20/js/dataTables.bootstrap4.min.js" crossorigin="anonymous"></script>
        <script src="{% static 'assets/demo/datatables-demo.js' %}"></script>
       <script src="https://use.fontawesome.com/releases/v5.7.0/css/all.css" integrity="sha384-lZN37f5QGtY3VHgisS14W3ExzMWZxybE1SJSEsQp9S+oqd12jhcu+A56Ebc1zFSJ" crossorigin="anonymous"> </script>
      <!-- jQuery -->
    <script src="{% static 'plugins/jquery/jquery.min.js' %}"></script>
    <!-- Bootstrap 4 -->
    <script src="{% static 'plugins/bootstrap/js/bootstrap.bundle.min.js' %}"></script>
    <!-- DataTables -->
    <script src="{% static 'plugins/datatables/jquery.dataTables.js' %}"></script>
    <script src="{% static 'plugins/datatables-bs4/js/dataTables.bootstrap4.js' %}"></script>
    <!-- AdminLTE App -->
    <script src="{% static 'dist/js/adminlte.min.js' %}"></script>
    <!-- AdminLTE for demo purposes -->
    <script src="{% static 'dist/js/demo.js' %}"></script>
    <!-- page script -->
    </body>
</html>